databases:
  - name: geospat
    databaseName: geospat
    user: geospat_user

services:
  - type: web
    name: geospat
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: geospat
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false